OC.data.calgoldBusinessTypes = [
  {'name': '541810', 'value': 'Advertising Agency'},
  {'name': '541870', 'value': 'Advertising Material Distribution Services'},
  {'name': '3724', 'value': 'Aircraft Engine and Engine Parts Manufacture'},
  {'name': '7900', 'value': 'Amusement and Recreation Services'},
  {'name': '453920', 'value': 'Art Dealer'},
  {'name': '541110', 'value': 'Attorney/Legal Services'},
  {'name': '4411', 'value': 'Automobile Dealer'},
  {'name': '7532', 'value': 'Automotive Body Repair'},
  {'name': '7536', 'value': 'Automotive Glass Replacement'},
  {'name': '811191', 'value': 'Automotive Oil Change and Lubrication'},
  {'name': '441310', 'value': 'Automotive Parts and Accessories'},
  {'name': '7538', 'value': 'Automotive Service and Repair'},
  {'name': '7230', 'value': 'Beauty Salon'},
  {'name': '0211', 'value': 'Beef Cattle Feedlot'},
  {'name': '112111', 'value': 'Beef Cattle Ranching and Farming'},
  {'name': '312112', 'value': 'Bottled Water'},
  {'name': '312120', 'value': 'Brewery'},
  {'name': '112320', 'value': 'Broilers and Other Meat Type Chicken Production'},
  {'name': '5390', 'value': 'Building Material and Supplies Dealer'},
  {'name': '811192', 'value': 'Car Wash'},
  {'name': '235510', 'value': 'Carpentry Contractor'},
  {'name': '561740', 'value': 'Carpet and Upholstery Cleaning Services'},
  {'name': '812220', 'value': 'Cemetery/ Crematory'},
  {'name': '2850', 'value': 'Chemical or Paint Formulation'},
  {'name': '624410', 'value': 'Child Day Care Services'},
  {'name': '8041', 'value': 'Chiropractor'},
  {'name': '448', 'value': 'Clothing and Clothing Accessories Store'},
  {'name': '312920', 'value': 'Coffee and Tea Manufacture'},
  {'name': '561440', 'value': 'Collection Agency'},
  {'name': '7211', 'value': 'Commercial Laundry'},
  {'name': '99991', 'value': 'Commercial Physical and Biological Research'},
  {'name': '7378', 'value': 'Computer Maintenance and Repair'},
  {'name': '7371', 'value': 'Computer Programming Services'},
  {'name': '54151', 'value': 'Computer Systems Design and Related Services'},
  {'name': '235710', 'value': 'Concrete Contractor'},
  {'name': '446120', 'value': 'Cosmetics, Beauty Supplies, and Perfume Store'},
  {'name': '492110', 'value': 'Courier'},
  {'name': '111', 'value': 'Crop Production'},
  {'name': '112120', 'value': 'Dairy Cattle and Milk Production'},
  {'name': '621210', 'value': 'Dentistry'},
  {'name': '541860', 'value': 'Direct Mail Advertising'},
  {'name': '454390', 'value': 'Direct Selling Establishment'},
  {'name': '312140', 'value': 'Distillery'},
  {'name': '311999', 'value': 'Dried and/or Dehydrated Food Manufacture'},
  {'name': '5910', 'value': 'Drug Store/Proprietary Store'},
  {'name': '7216', 'value': 'Dry-Cleaning Plant'},
  {'name': '235420', 'value': 'Drywall, Plastering, Acoustical, and Insulation Contractor'},
  {'name': '235310', 'value': 'Electrical Contractor'},
  {'name': '3600', 'value': 'Electronic and Other Electrical Equipment Manufacturing'},
  {'name': '454110', 'value': 'Electronic Shopping and Mail Order House'},
  {'name': '8710', 'value': 'Engineering and Architectural Services'},
  {'name': '8700', 'value': 'Engineering and Management Services'},
  {'name': '541620', 'value': 'Environmental Consulting Services'},
  {'name': '561710', 'value': 'Exterminating and Pest Control Services'},
  {'name': '3400', 'value': 'Fabricated Metal Products'},
  {'name': '422910', 'value': 'Farm Supplies Wholesaler'},
  {'name': '31193', 'value': 'Flavoring Syrup and Concentrate Manufacture'},
  {'name': '235520', 'value': 'Floor Laying and/or Other Floor Contractor'},
  {'name': '5193', 'value': 'Flowers and  Florists Supplies Distribution'},
  {'name': '311511', 'value': 'Fluid Milk Manufacture'},
  {'name': '446191', 'value': 'Food (Health) Supplement Store'},
  {'name': '2099', 'value': 'Food Manufacture'},
  {'name': '2033', 'value': 'Fruit and Vegetable Canning'},
  {'name': '445230', 'value': 'Fruit and Vegetable Market'},
  {'name': '442', 'value': 'Furniture and Home Furnishings Store'},
  {'name': '337', 'value': 'Furniture and Related Products Manufacture'},
  {'name': '2399', 'value': 'Garment Manufacture'},
  {'name': '5540', 'value': 'Gasoline Service Station'},
  {'name': '7300', 'value': 'General Business Information'},
  {'name': '453220', 'value': 'Gift, Novelty, and Souvenir Store'},
  {'name': '235920', 'value': 'Glass and Glazing Contractor'},
  {'name': '541430', 'value': 'Graphic Design Services'},
  {'name': '5410', 'value': 'Grocery Store'},
  {'name': '81211', 'value': 'Hair, Nail, and Skin Care Services'},
  {'name': '451120', 'value': 'Hobby, Toy and Game Store'},
  {'name': '721110', 'value': 'Hotel (except Casino Hotels)/Motel'},
  {'name': '541612', 'value': 'Human Resources and Executive Search Consulting Services'},
  {'name': '312113', 'value': 'Ice Manufacture'},
  {'name': '5099', 'value': 'Import/Export'},
  {'name': '4953', 'value': 'Incineration Operation for Refuse'},
  {'name': '1629', 'value': 'Industrial Nonbuilding Construction'},
  {'name': '524210', 'value': 'Insurance Agency and Brokerage'},
  {'name': '561611', 'value': 'Investigation Services'},
  {'name': '334517', 'value': 'Irradiation Apparatus Manufacture'},
  {'name': '7349', 'value': 'Janitorial Cleaning Maintenance Services'},
  {'name': '561730', 'value': 'Landscape Services'},
  {'name': '485320', 'value': 'Limousine Service'},
  {'name': '4214', 'value': 'Local Trucking With Storage'},
  {'name': '4212', 'value': 'Local Trucking Without Storage'},
  {'name': '322223', 'value': 'Manufacture of Bags: Plastics, Foil, & Coated'},
  {'name': '541613', 'value': 'Marketing Consulting Services'},
  {'name': '235410', 'value': 'Masonry and Stone Contractor'},
  {'name': '4215', 'value': 'Messenger Service'},
  {'name': '3410', 'value': 'Metal Cans and Shipping Containers Manufacture'},
  {'name': '3479', 'value': 'Metal Coating and Allied Services'},
  {'name': '453', 'value': 'Miscellaneous Store Retailer'},
  {'name': '512', 'value': 'Motion Picture and Sound Recording'},
  {'name': '334510', 'value': 'Navigational, Measuring, Electromedical, and Control Instruments'},
  {'name': '541120', 'value': 'Notary Public'},
  {'name': '623', 'value': 'Nursing and Residential Care Facility'},
  {'name': '514191', 'value': 'On-Line Information Services'},
  {'name': '621320', 'value': 'Optometry'},
  {'name': '45439', 'value': 'Other Direct Selling Establishment'},
  {'name': '561790', 'value': 'Other Services to Buildings and Dwellings'},
  {'name': '235210', 'value': 'Painting and Wall Covering Contractor'},
  {'name': '325320', 'value': 'Pesticide and Other Agricultural Chemical Manufacture'},
  {'name': '453910', 'value': 'Pet and Pet Supplies Store'},
  {'name': '812921', 'value': 'Photofinishing Laboratory (except One-Hour)'},
  {'name': '54192', 'value': 'Photographic Services'},
  {'name': '62111', 'value': 'Physician'},
  {'name': '3471', 'value': 'Plating and Polishing Services'},
  {'name': '3430', 'value': 'Plumbing and Heating Equipment Manufacture, Except Electric'},
  {'name': '235110', 'value': 'Plumbing, Heating, and Air-Conditioning Contractor'},
  {'name': '115114', 'value': 'Postharvest Crop Activities (except Cotton Ginning)'},
  {'name': '311615', 'value': 'Poultry Processing'},
  {'name': '2750', 'value': 'Print Shop'},
  {'name': '3672', 'value': 'Printed Circuit Boards Manufacture'},
  {'name': '7622', 'value': 'Radio and Television Repair'},
  {'name': '562111', 'value': 'Recycling Center'},
  {'name': '561491', 'value': 'Repossession Services'},
  {'name': '5812', 'value': 'Restaurant'},
  {'name': '5260', 'value': 'Retail Nursery/Garden Store'},
  {'name': '235610', 'value': 'Roofing, Siding, and Sheet Metal Contractor'},
  {'name': '561612', 'value': 'Security Guard and Patrol Services'},
  {'name': '3674', 'value': 'Semiconductors And Related Device Manufacture'},
  {'name': '4111', 'value': 'Shuttle Bus Service'},
  {'name': '5963', 'value': 'Sidewalk and Street Vending'},
  {'name': '233210', 'value': 'Single Family Housing Construction'},
  {'name': '7533', 'value': 'Smog Test Shop'},
  {'name': '312111', 'value': 'Soft Drink Manufacture'},
  {'name': '451110', 'value': 'Sporting Goods Store'},
  {'name': '339112', 'value': 'Surgical and Medical Instruments Manufacture'},
  {'name': '339113', 'value': 'Surgical Appliance and Supplies Manufacture'},
  {'name': '8900', 'value': 'Tax Exempt Status'},
  {'name': '541213', 'value': 'Tax Preparation Services'},
  {'name': '485310', 'value': 'Taxi Service'},
  {'name': '541380', 'value': 'Testing Laboratory'},
  {'name': '56151', 'value': 'Travel Agency'},
  {'name': '453310', 'value': 'Used Merchandise Store'},
  {'name': '454210', 'value': 'Vending Machine Operator'},
  {'name': '541940', 'value': 'Veterinary Services'},
  {'name': '532230', 'value': 'Video Tape and Disc Rental'},
  {'name': '8249', 'value': 'Vocational School'},
  {'name': '312130', 'value': 'Winery'},
  {'name': '337110', 'value': 'Wood Kitchen Cabinet and Countertop Manufacture'},
  {'name': '235940', 'value': 'Wrecking and Demolition Contractor'},
];                
